artifact_location: file:///C:/Users/PC/Desktop/clase4/pontia-mlops-tutorial/no_mlflow_found/0
creation_time: 1762280841066
experiment_id: '0'
last_update_time: 1762280841066
lifecycle_stage: active
name: Default
