artifact_location: file:///C:/Users/PC/Desktop/clase4/pontia-mlops-tutorial/no_mlflow_found/164429676740345108
creation_time: 1762280841085
experiment_id: '164429676740345108'
last_update_time: 1762280841085
lifecycle_stage: active
name: no_experiment_name_found
